In [1]:
# numpy, pandas, scikit-learn 패키지 설치
!pip install numpy pandas scikit-learn

Requirement already satisfied: numpy in c:\users\itsc\pycharmprojects\pythonproject\.venv\lib\site-packages (2.2.6)
Collecting pandas
  Downloading pandas-2.3.1-cp313-cp313-win_amd64.whl.metadata (19 kB)
Collecting scikit-learn
  Downloading scikit_learn-1.7.1-cp313-cp313-win_amd64.whl.metadata (11 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\itsc\pycharmprojects\pythonproject\.venv\lib\site-packages (from pandas) (2.9.0.post0)
Collecting pytz>=2020.1 (from pandas)
  Downloading pytz-2025.2-py2.py3-none-any.whl.metadata (22 kB)
Collecting tzdata>=2022.7 (from pandas)
  Using cached tzdata-2025.2-py2.py3-none-any.whl.metadata (1.4 kB)
Collecting scipy>=1.8.0 (from scikit-learn)
  Downloading scipy-1.16.0-cp313-cp313-win_amd64.whl.metadata (60 kB)
Collecting joblib>=1.2.0 (from scikit-learn)
  Downloading joblib-1.5.1-py3-none-any.whl.metadata (5.6 kB)
Collecting threadpoolctl>=3.1.0 (from scikit-learn)
  Downloading threadpoolctl-3.6.0-py3-none-any.whl.metadata (13 kB)
Requirement already satisfied: six>=1.5 in c:\users\itsc\pycharmprojects\pythonproject\.venv\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-2.3.1-cp313-cp313-win_amd64.whl (11.0 MB)
   ---------------------------------------- 0.0/11.0 MB ? eta -:--:--
   ------ --------------------------------- 1.8/11.0 MB 9.1 MB/s eta 0:00:02
   ------------- -------------------------- 3.7/11.0 MB 9.1 MB/s eta 0:00:01
   ----------------- ---------------------- 4.7/11.0 MB 8.5 MB/s eta 0:00:01
   -------------------- ------------------- 5.5/11.0 MB 7.1 MB/s eta 0:00:01
   ---------------------- ----------------- 6.3/11.0 MB 6.5 MB/s eta 0:00:01
   -------------------------- ------------- 7.3/11.0 MB 6.0 MB/s eta 0:00:01
   ----------------------------- ---------- 8.1/11.0 MB 5.7 MB/s eta 0:00:01
   --------------------------------- ------ 9.2/11.0 MB 5.6 MB/s eta 0:00:01
   ------------------------------------- -- 10.2/11.0 MB 5.6 MB/s eta 0:00:01
   ---------------------------------------- 11.0/11.0 MB 5.4 MB/s eta 0:00:00
Downloading scikit_learn-1.7.1-cp313-cp313-win_amd64.whl (8.7 MB)
   ---------------------------------------- 0.0/8.7 MB ? eta -:--:--
   ------ --------------------------------- 1.3/8.7 MB 8.0 MB/s eta 0:00:01
   ---------- ----------------------------- 2.4/8.7 MB 6.2 MB/s eta 0:00:02
   --------------- ------------------------ 3.4/8.7 MB 5.7 MB/s eta 0:00:01
   -------------------- ------------------- 4.5/8.7 MB 5.7 MB/s eta 0:00:01
   ------------------------- -------------- 5.5/8.7 MB 5.5 MB/s eta 0:00:01
   ---------------------------- ----------- 6.3/8.7 MB 5.1 MB/s eta 0:00:01
   -------------------------------- ------- 7.1/8.7 MB 4.9 MB/s eta 0:00:01
   ------------------------------------- -- 8.1/8.7 MB 4.8 MB/s eta 0:00:01
   ---------------------------------------  8.7/8.7 MB 4.9 MB/s eta 0:00:01
   ---------------------------------------- 8.7/8.7 MB 4.5 MB/s eta 0:00:00
Downloading joblib-1.5.1-py3-none-any.whl (307 kB)
Downloading pytz-2025.2-py2.py3-none-any.whl (509 kB)
Downloading scipy-1.16.0-cp313-cp313-win_amd64.whl (38.4 MB)
   ---------------------------------------- 0.0/38.4 MB ? eta -:--:--
   - -------------------------------------- 1.0/38.4 MB 5.6 MB/s eta 0:00:07
   -- ------------------------------------- 2.1/38.4 MB 5.1 MB/s eta 0:00:08
   --- ------------------------------------ 2.9/38.4 MB 4.6 MB/s eta 0:00:08
   --- ------------------------------------ 3.7/38.4 MB 4.3 MB/s eta 0:00:09
   ---- ----------------------------------- 4.5/38.4 MB 4.1 MB/s eta 0:00:09
   ----- ---------------------------------- 5.2/38.4 MB 4.1 MB/s eta 0:00:09
   ------ --------------------------------- 6.0/38.4 MB 4.0 MB/s eta 0:00:09
   ------- -------------------------------- 6.8/38.4 MB 4.0 MB/s eta 0:00:08
   ------- -------------------------------- 7.6/38.4 MB 4.0 MB/s eta 0:00:08
   -------- ------------------------------- 8.1/38.4 MB 3.9 MB/s eta 0:00:08
   --------- ------------------------------ 8.9/38.4 MB 3.8 MB/s eta 0:00:08
   ---------- ----------------------------- 9.7/38.4 MB 3.8 MB/s eta 0:00:08
   ---------- ----------------------------- 10.5/38.4 MB 3.8 MB/s eta 0:00:08
   ----------- ---------------------------- 11.3/38.4 MB 3.8 MB/s eta 0:00:08
   ------------ --------------------------- 11.8/38.4 MB 3.7 MB/s eta 0:00:08
   ------------- -------------------------- 12.6/38.4 MB 3.7 MB/s eta 0:00:07
   ------------- -------------------------- 13.4/38.4 MB 3.7 MB/s eta 0:00:07
   --------------- ------------------------ 14.4/38.4 MB 3.8 MB/s eta 0:00:07
   ---------------- ----------------------- 15.7/38.4 MB 3.9 MB/s eta 0:00:06
   ----------------- ---------------------- 17.0/38.4 MB 4.0 MB/s eta 0:00:06
   ------------------- -------------------- 18.9/38.4 MB 4.2 MB/s eta 0:00:05
   ---------------------- ----------------- 21.2/38.4 MB 4.5 MB/s eta 0:00:04
   ------------------------ --------------- 23.6/38.4 MB 4.8 MB/s eta 0:00:04
   --------------------------- ------------ 26.0/38.4 MB 5.1 MB/s eta 0:00:03
   ----------------------------- ---------- 28.0/38.4 MB 5.3 MB/s eta 0:00:02
   ------------------------------- -------- 30.7/38.4 MB 5.6 MB/s eta 0:00:02
   ---------------------------------- ----- 33.0/38.4 MB 5.8 MB/s eta 0:00:01
   ------------------------------------ --- 35.4/38.4 MB 6.0 MB/s eta 0:00:01
   ---------------------------------------  37.7/38.4 MB 6.2 MB/s eta 0:00:01
   ---------------------------------------- 38.4/38.4 MB 6.1 MB/s eta 0:00:00
Downloading threadpoolctl-3.6.0-py3-none-any.whl (18 kB)
Using cached tzdata-2025.2-py2.py3-none-any.whl (347 kB)
Installing collected packages: pytz, tzdata, threadpoolctl, scipy, joblib, scikit-learn, pandas

   ---------------------------------------- 0/7 [pytz]
   ---------------------------------------- 0/7 [pytz]
   ----- ---------------------------------- 1/7 [tzdata]
   ----- ---------------------------------- 1/7 [tzdata]
   ----- ---------------------------------- 1/7 [tzdata]
   ----- ---------------------------------- 1/7 [tzdata]
   ----------------- ---------------------- 3/7 [scipy]
   ----------------- ---------------------- 3/7 [scipy]
   ----------------- ---------------------- 3/7 [scipy]
   ----------------- ---------------------- 3/7 [scipy]
   ----------------- ---------------------- 3/7 [scipy]
   ----------------- ---------------------- 3/7 [scipy]
   ----------------- ---------------------- 3/7 [scipy]
   ----------------- ---------------------- 3/7 [scipy]
   ----------------- ---------------------- 3/7 [scipy]
   ----------------- ---------------------- 3/7 [scipy]
   ----------------- ---------------------- 3/7 [scipy]
   ----------------- ---------------------- 3/7 [scipy]
   ----------------- ---------------------- 3/7 [scipy]
   ----------------- ---------------------- 3/7 [scipy]
   ----------------- ---------------------- 3/7 [scipy]
   ----------------- ---------------------- 3/7 [scipy]
   ----------------- ---------------------- 3/7 [scipy]
   ----------------- ---------------------- 3/7 [scipy]
   ----------------- ---------------------- 3/7 [scipy]
   ----------------- ---------------------- 3/7 [scipy]
   ----------------- ---------------------- 3/7 [scipy]
   ----------------- ---------------------- 3/7 [scipy]
   ----------------- ---------------------- 3/7 [scipy]
   ----------------- ---------------------- 3/7 [scipy]
   ----------------- ---------------------- 3/7 [scipy]
   ----------------- ---------------------- 3/7 [scipy]
   ----------------- ---------------------- 3/7 [scipy]
   ----------------- ---------------------- 3/7 [scipy]
   ----------------- ---------------------- 3/7 [scipy]
   ----------------- ---------------------- 3/7 [scipy]
   ----------------- ---------------------- 3/7 [scipy]
   ----------------- ---------------------- 3/7 [scipy]
   ----------------- ---------------------- 3/7 [scipy]
   ----------------- ---------------------- 3/7 [scipy]
   ----------------- ---------------------- 3/7 [scipy]
   ----------------- ---------------------- 3/7 [scipy]
   ----------------- ---------------------- 3/7 [scipy]
   ----------------- ---------------------- 3/7 [scipy]
   ----------------- ---------------------- 3/7 [scipy]
   ----------------- ---------------------- 3/7 [scipy]
   ----------------- ---------------------- 3/7 [scipy]
   ----------------- ---------------------- 3/7 [scipy]
   ----------------- ---------------------- 3/7 [scipy]
   ----------------- ---------------------- 3/7 [scipy]
   ----------------- ---------------------- 3/7 [scipy]
   ----------------- ---------------------- 3/7 [scipy]
   ----------------- ---------------------- 3/7 [scipy]
   ----------------- ---------------------- 3/7 [scipy]
   ----------------- ---------------------- 3/7 [scipy]
   ----------------- ---------------------- 3/7 [scipy]
   ----------------- ---------------------- 3/7 [scipy]
   ----------------- ---------------------- 3/7 [scipy]
   ----------------- ---------------------- 3/7 [scipy]
   ----------------- ---------------------- 3/7 [scipy]
   ----------------- ---------------------- 3/7 [scipy]
   ----------------- ---------------------- 3/7 [scipy]
   ----------------- ---------------------- 3/7 [scipy]
   ----------------- ---------------------- 3/7 [scipy]
   ----------------- ---------------------- 3/7 [scipy]
   ----------------- ---------------------- 3/7 [scipy]
   ----------------- ---------------------- 3/7 [scipy]
   ----------------- ---------------------- 3/7 [scipy]
   ----------------- ---------------------- 3/7 [scipy]
   ----------------- ---------------------- 3/7 [scipy]
   ----------------- ---------------------- 3/7 [scipy]
   ----------------- ---------------------- 3/7 [scipy]
   ----------------- ---------------------- 3/7 [scipy]
   ----------------- ---------------------- 3/7 [scipy]
   ----------------- ---------------------- 3/7 [scipy]
   ----------------- ---------------------- 3/7 [scipy]
   ----------------- ---------------------- 3/7 [scipy]
   ----------------- ---------------------- 3/7 [scipy]
   ----------------- ---------------------- 3/7 [scipy]
   ----------------- ---------------------- 3/7 [scipy]
   ----------------- ---------------------- 3/7 [scipy]
   ----------------- ---------------------- 3/7 [scipy]
   ----------------- ---------------------- 3/7 [scipy]
   ----------------- ---------------------- 3/7 [scipy]
   ----------------- ---------------------- 3/7 [scipy]
   ----------------- ---------------------- 3/7 [scipy]
   ----------------- ---------------------- 3/7 [scipy]
   ----------------- ---------------------- 3/7 [scipy]
   ----------------- ---------------------- 3/7 [scipy]
   ----------------- ---------------------- 3/7 [scipy]
   ----------------- ---------------------- 3/7 [scipy]
   ----------------- ---------------------- 3/7 [scipy]
   ----------------- ---------------------- 3/7 [scipy]
   ----------------- ---------------------- 3/7 [scipy]
   ----------------- ---------------------- 3/7 [scipy]
   ----------------- ---------------------- 3/7 [scipy]
   ----------------- ---------------------- 3/7 [scipy]
   ----------------- ---------------------- 3/7 [scipy]
   ----------------- ---------------------- 3/7 [scipy]
   ----------------- ---------------------- 3/7 [scipy]
   ---------------------- ----------------- 4/7 [joblib]
   ---------------------- ----------------- 4/7 [joblib]
   ---------------------- ----------------- 4/7 [joblib]
   ---------------------- ----------------- 4/7 [joblib]
   ---------------------- ----------------- 4/7 [joblib]
   ---------------------- ----------------- 4/7 [joblib]
   ---------------------- ----------------- 4/7 [joblib]
   ---------------------- ----------------- 4/7 [joblib]
   ---------------------- ----------------- 4/7 [joblib]
   ---------------------- ----------------- 4/7 [joblib]
   ---------------------- ----------------- 4/7 [joblib]
   ---------------------- ----------------- 4/7 [joblib]
   ---------------------- ----------------- 4/7 [joblib]
   ---------------------- ----------------- 4/7 [joblib]
   ---------------------- ----------------- 4/7 [joblib]
   ---------------------- ----------------- 4/7 [joblib]
   ---------------------- ----------------- 4/7 [joblib]
   ---------------------- ----------------- 4/7 [joblib]
   ---------------------- ----------------- 4/7 [joblib]
   ---------------------- ----------------- 4/7 [joblib]
   ---------------------- ----------------- 4/7 [joblib]
   ---------------------- ----------------- 4/7 [joblib]
   ---------------------- ----------------- 4/7 [joblib]
   ---------------------- ----------------- 4/7 [joblib]
   ---------------------- ----------------- 4/7 [joblib]
   ---------------------- ----------------- 4/7 [joblib]
   ---------------------- ----------------- 4/7 [joblib]
   ---------------------- ----------------- 4/7 [joblib]
   ---------------------- ----------------- 4/7 [joblib]
   ---------------------- ----------------- 4/7 [joblib]
   ---------------------- ----------------- 4/7 [joblib]
   ---------------------- ----------------- 4/7 [joblib]
   ---------------------- ----------------- 4/7 [joblib]
   ---------------------- ----------------- 4/7 [joblib]
   ---------------------- ----------------- 4/7 [joblib]
   ---------------------- ----------------- 4/7 [joblib]
   ---------------------- ----------------- 4/7 [joblib]
   ---------------------- ----------------- 4/7 [joblib]
   ---------------------- ----------------- 4/7 [joblib]
   ---------------------- ----------------- 4/7 [joblib]
   ---------------------- ----------------- 4/7 [joblib]
   ---------------------- ----------------- 4/7 [joblib]
   ---------------------- ----------------- 4/7 [joblib]
   ---------------------------- ----------- 5/7 [scikit-learn]
   ---------------------------- ----------- 5/7 [scikit-learn]
   ---------------------------- ----------- 5/7 [scikit-learn]
   ---------------------------- ----------- 5/7 [scikit-learn]
   ---------------------------- ----------- 5/7 [scikit-learn]
   ---------------------------- ----------- 5/7 [scikit-learn]
   ---------------------------- ----------- 5/7 [scikit-learn]
   ---------------------------- ----------- 5/7 [scikit-learn]
   ---------------------------- ----------- 5/7 [scikit-learn]
   ---------------------------- ----------- 5/7 [scikit-learn]
   ---------------------------- ----------- 5/7 [scikit-learn]
   ---------------------------- ----------- 5/7 [scikit-learn]
   ---------------------------- ----------- 5/7 [scikit-learn]
   ---------------------------- ----------- 5/7 [scikit-learn]
   ---------------------------- ----------- 5/7 [scikit-learn]
   ---------------------------- ----------- 5/7 [scikit-learn]
   ---------------------------- ----------- 5/7 [scikit-learn]
   ---------------------------- ----------- 5/7 [scikit-learn]
   ---------------------------- ----------- 5/7 [scikit-learn]
   ---------------------------- ----------- 5/7 [scikit-learn]
   ---------------------------- ----------- 5/7 [scikit-learn]
   ---------------------------- ----------- 5/7 [scikit-learn]
   ---------------------------- ----------- 5/7 [scikit-learn]
   ---------------------------- ----------- 5/7 [scikit-learn]
   ---------------------------- ----------- 5/7 [scikit-learn]
   ---------------------------- ----------- 5/7 [scikit-learn]
   ---------------------------- ----------- 5/7 [scikit-learn]
   ---------------------------- ----------- 5/7 [scikit-learn]
   ---------------------------- ----------- 5/7 [scikit-learn]
   ---------------------------- ----------- 5/7 [scikit-learn]
   ---------------------------- ----------- 5/7 [scikit-learn]
   ---------------------------- ----------- 5/7 [scikit-learn]
   ---------------------------- ----------- 5/7 [scikit-learn]
   ---------------------------- ----------- 5/7 [scikit-learn]
   ---------------------------- ----------- 5/7 [scikit-learn]
   ---------------------------- ----------- 5/7 [scikit-learn]
   ---------------------------- ----------- 5/7 [scikit-learn]
   ---------------------------- ----------- 5/7 [scikit-learn]
   ---------------------------- ----------- 5/7 [scikit-learn]
   ---------------------------- ----------- 5/7 [scikit-learn]
   ---------------------------- ----------- 5/7 [scikit-learn]
   ---------------------------- ----------- 5/7 [scikit-learn]
   ---------------------------- ----------- 5/7 [scikit-learn]
   ---------------------------- ----------- 5/7 [scikit-learn]
   ---------------------------- ----------- 5/7 [scikit-learn]
   ---------------------------------- ----- 6/7 [pandas]
   ---------------------------------- ----- 6/7 [pandas]
   ---------------------------------- ----- 6/7 [pandas]
   ---------------------------------- ----- 6/7 [pandas]
   ---------------------------------- ----- 6/7 [pandas]
   ---------------------------------- ----- 6/7 [pandas]
   ---------------------------------- ----- 6/7 [pandas]
   ---------------------------------- ----- 6/7 [pandas]
   ---------------------------------- ----- 6/7 [pandas]
   ---------------------------------- ----- 6/7 [pandas]
   ---------------------------------- ----- 6/7 [pandas]
   ---------------------------------- ----- 6/7 [pandas]
   ---------------------------------- ----- 6/7 [pandas]
   ---------------------------------- ----- 6/7 [pandas]
   ---------------------------------- ----- 6/7 [pandas]
   ---------------------------------- ----- 6/7 [pandas]
   ---------------------------------- ----- 6/7 [pandas]
   ---------------------------------- ----- 6/7 [pandas]
   ---------------------------------- ----- 6/7 [pandas]
   ---------------------------------- ----- 6/7 [pandas]
   ---------------------------------- ----- 6/7 [pandas]
   ---------------------------------- ----- 6/7 [pandas]
   ---------------------------------- ----- 6/7 [pandas]
   ---------------------------------- ----- 6/7 [pandas]
   ---------------------------------- ----- 6/7 [pandas]
   ---------------------------------- ----- 6/7 [pandas]
   ---------------------------------- ----- 6/7 [pandas]
   ---------------------------------- ----- 6/7 [pandas]
   ---------------------------------- ----- 6/7 [pandas]
   ---------------------------------- ----- 6/7 [pandas]
   ---------------------------------- ----- 6/7 [pandas]
   ---------------------------------- ----- 6/7 [pandas]
   ---------------------------------- ----- 6/7 [pandas]
   ---------------------------------- ----- 6/7 [pandas]
   ---------------------------------- ----- 6/7 [pandas]
   ---------------------------------- ----- 6/7 [pandas]
   ---------------------------------- ----- 6/7 [pandas]
   ---------------------------------- ----- 6/7 [pandas]
   ---------------------------------- ----- 6/7 [pandas]
   ---------------------------------- ----- 6/7 [pandas]
   ---------------------------------- ----- 6/7 [pandas]
   ---------------------------------- ----- 6/7 [pandas]
   ---------------------------------- ----- 6/7 [pandas]
   ---------------------------------- ----- 6/7 [pandas]
   ---------------------------------- ----- 6/7 [pandas]
   ---------------------------------- ----- 6/7 [pandas]
   ---------------------------------- ----- 6/7 [pandas]
   ---------------------------------- ----- 6/7 [pandas]
   ---------------------------------- ----- 6/7 [pandas]
   ---------------------------------- ----- 6/7 [pandas]
   ---------------------------------- ----- 6/7 [pandas]
   ---------------------------------- ----- 6/7 [pandas]
   ---------------------------------- ----- 6/7 [pandas]
   ---------------------------------- ----- 6/7 [pandas]
   ---------------------------------- ----- 6/7 [pandas]
   ---------------------------------- ----- 6/7 [pandas]
   ---------------------------------- ----- 6/7 [pandas]
   ---------------------------------- ----- 6/7 [pandas]
   ---------------------------------- ----- 6/7 [pandas]

In [2]:
import sklearn

print(sklearn.__version__)

1.7.1

In [4]:
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split

import pandas as pd

In [5]:
# 붓꽃 데이터 세트 로딩
iris = load_iris()

iris

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
        [5.5, 4.2, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.2],
        [5. , 3.2, 1.2, 0.2],
        [5.5, 3.5, 1.3, 0.2],
        [4.9, 3.6, 1.4, 0.1],
        [4.4, 3. , 1.3, 0.2],
        [5.1, 3.4, 1.5, 0.2],
        [5. , 3.5, 1.3, 0.3],
        [4.5, 2.3, 1.3, 0.3],
        [4.4, 3.2, 1.3, 0.2],
        [5. , 3.5, 1.6, 0.6],
        [5.1, 3.8, 1.9, 0.4],
        [4.8, 3. , 1.4, 0.3],
        [5.1, 3.8, 1.6, 0.2],
        [4.6, 3.2, 1.4, 0.2],
        [5.3, 3.7, 1.5, 0.2],
        [5. , 3.3, 1.4, 0.2],
        [7. , 3.2, 4.7, 1.4],
        [6.4, 3.2, 4.5, 1.5],
        [6.9, 3.1, 4.9, 1.5],
        [5.5, 2.3, 4. , 1.3],
        [6.5, 2.8, 4.6, 1.5],
        [5.7, 2.8, 4.5, 1.3],
        [6.3, 3.3, 4.7, 1.6],
        [4.9, 2.4, 3.3, 1. ],
        [6.6, 2.9, 4.6, 1.3],
        [5.2, 2.7, 3.9, 1.4],
        [5. , 2. , 3.5, 1. ],
        [5.9, 3. , 4.2, 1.5],
        [6. , 2.2, 4. , 1. ],
        [6.1, 2.9, 4.7, 1.4],
        [5.6, 2.9, 3.6, 1.3],
        [6.7, 3.1, 4.4, 1.4],
        [5.6, 3. , 4.5, 1.5],
        [5.8, 2.7, 4.1, 1. ],
        [6.2, 2.2, 4.5, 1.5],
        [5.6, 2.5, 3.9, 1.1],
        [5.9, 3.2, 4.8, 1.8],
        [6.1, 2.8, 4. , 1.3],
        [6.3, 2.5, 4.9, 1.5],
        [6.1, 2.8, 4.7, 1.2],
        [6.4, 2.9, 4.3, 1.3],
        [6.6, 3. , 4.4, 1.4],
        [6.8, 2.8, 4.8, 1.4],
        [6.7, 3. , 5. , 1.7],
        [6. , 2.9, 4.5, 1.5],
        [5.7, 2.6, 3.5, 1. ],
        [5.5, 2.4, 3.8, 1.1],
        [5.5, 2.4, 3.7, 1. ],
        [5.8, 2.7, 3.9, 1.2],
        [6. , 2.7, 5.1, 1.6],
        [5.4, 3. , 4.5, 1.5],
        [6. , 3.4, 4.5, 1.6],
        [6.7, 3.1, 4.7, 1.5],
        [6.3, 2.3, 4.4, 1.3],
        [5.6, 3. , 4.1, 1.3],
        [5.5, 2.5, 4. , 1.3],
        [5.5, 2.6, 4.4, 1.2],
        [6.1, 3. , 4.6, 1.4],
        [5.8, 2.6, 4. , 1.2],
        [5. , 2.3, 3.3, 1. ],
        [5.6, 2.7, 4.2, 1.3],
        [5.7, 3. , 4.2, 1.2],
        [5.7, 2.9, 4.2, 1.3],
        [6.2, 2.9, 4.3, 1.3],
        [5.1, 2.5, 3. , 1.1],
        [5.7, 2.8, 4.1, 1.3],
        [6.3, 3.3, 6. , 2.5],
        [5.8, 2.7, 5.1, 1.9],
        [7.1, 3. , 5.9, 2.1],
        [6.3, 2.9, 5.6, 1.8],
        [6.5, 3. , 5.8, 2.2],
        [7.6, 3. , 6.6, 2.1],
        [4.9, 2.5, 4.5, 1.7],
        [7.3, 2.9, 6.3, 1.8],
        [6.7, 2.5, 5.8, 1.8],
        [7.2, 3.6, 6.1, 2.5],
        [6.5, 3.2, 5.1, 2. ],
        [6.4, 2.7, 5.3, 1.9],
        [6.8, 3. , 5.5, 2.1],
        [5.7, 2.5, 5. , 2. ],
        [5.8, 2.8, 5.1, 2.4],
        [6.4, 3.2, 5.3, 2.3],
        [6.5, 3. , 5.5, 1.8],
        [7.7, 3.8, 6.7, 2.2],
        [7.7, 2.6, 6.9, 2.3],
        [6. , 2.2, 5. , 1.5],
        [6.9, 3.2, 5.7, 2.3],
        [5.6, 2.8, 4.9, 2. ],
        [7.7, 2.8, 6.7, 2. ],
        [6.3, 2.7, 4.9, 1.8],
        [6.7, 3.3, 5.7, 2.1],
        [7.2, 3.2, 6. , 1.8],
        [6.2, 2.8, 4.8, 1.8],
        [6.1, 3. , 4.9, 1.8],
        [6.4, 2.8, 5.6, 2.1],
        [7.2, 3. , 5.8, 1.6],
        [7.4, 2.8, 6.1, 1.9],
        [7.9, 3.8, 6.4, 2. ],
        [6.4, 2.8, 5.6, 2.2],
        [6.3, 2.8, 5.1, 1.5],
        [6.1, 2.6, 5.6, 1.4],
        [7.7, 3. , 6.1, 2.3],
        [6.3, 3.4, 5.6, 2.4],
        [6.4, 3.1, 5.5, 1.8],
        [6. , 3. , 4.8, 1.8],
        [6.9, 3.1, 5.4, 2.1],
        [6.7, 3.1, 5.6, 2.4],
        [6.9, 3.1, 5.1, 2.3],
        [5.8, 2.7, 5.1, 1.9],
        [6.8, 3.2, 5.9, 2.3],
        [6.7, 3.3, 5.7, 2.5],
        [6.7, 3. , 5.2, 2.3],
        [6.3, 2.5, 5. , 1.9],
        [6.5, 3. , 5.2, 2. ],
        [6.2, 3.4, 5.4, 2.3],
        [5.9, 3. , 5.1, 1.8]]),
 'target': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2]),
 'frame': None,
 'target_names': array(['setosa', 'versicolor', 'virginica'], dtype='<U10'),
 'DESCR': '.. _iris_dataset:\n\nIris plants dataset\n--------------------\n\n**Data Set Characteristics:**\n\n:Number of Instances: 150 (50 in each of three classes)\n:Number of Attributes: 4 numeric, predictive attributes and the class\n:Attribute Information:\n    - sepal length in cm\n    - sepal width in cm\n    - petal length in cm\n    - petal width in cm\n    - class:\n            - Iris-Setosa\n            - Iris-Versicolour\n            - Iris-Virginica\n\n:Summary Statistics:\n\n============== ==== ==== ======= ===== ====================\n                Min  Max   Mean    SD   Class Correlation\n============== ==== ==== ======= ===== ====================\nsepal length:   4.3  7.9   5.84   0.83    0.7826\nsepal width:    2.0  4.4   3.05   0.43   -0.4194\npetal length:   1.0  6.9   3.76   1.76    0.9490  (high!)\npetal width:    0.1  2.5   1.20   0.76    0.9565  (high!)\n============== ==== ==== ======= ===== ====================\n\n:Missing Attribute Values: None\n:Class Distribution: 33.3% for each of 3 classes.\n:Creator: R.A. Fisher\n:Donor: Michael Marshall (MARSHALL%PLU@io.arc.nasa.gov)\n:Date: July, 1988\n\nThe famous Iris database, first used by Sir R.A. Fisher. The dataset is taken\nfrom Fisher\'s paper. Note that it\'s the same as in R, but not as in the UCI\nMachine Learning Repository, which has two wrong data points.\n\nThis is perhaps the best known database to be found in the\npattern recognition literature.  Fisher\'s paper is a classic in the field and\nis referenced frequently to this day.  (See Duda & Hart, for example.)  The\ndata set contains 3 classes of 50 instances each, where each class refers to a\ntype of iris plant.  One class is linearly separable from the other 2; the\nlatter are NOT linearly separable from each other.\n\n.. dropdown:: References\n\n  - Fisher, R.A. "The use of multiple measurements in taxonomic problems"\n    Annual Eugenics, 7, Part II, 179-188 (1936); also in "Contributions to\n    Mathematical Statistics" (John Wiley, NY, 1950).\n  - Duda, R.O., & Hart, P.E. (1973) Pattern Classification and Scene Analysis.\n    (Q327.D83) John Wiley & Sons.  ISBN 0-471-22361-1.  See page 218.\n  - Dasarathy, B.V. (1980) "Nosing Around the Neighborhood: A New System\n    Structure and Classification Rule for Recognition in Partially Exposed\n    Environments".  IEEE Transactions on Pattern Analysis and Machine\n    Intelligence, Vol. PAMI-2, No. 1, 67-71.\n  - Gates, G.W. (1972) "The Reduced Nearest Neighbor Rule".  IEEE Transactions\n    on Information Theory, May 1972, 431-433.\n  - See also: 1988 MLC Proceedings, 54-64.  Cheeseman et al"s AUTOCLASS II\n    conceptual clustering system finds 3 classes in the data.\n  - Many, many more ...\n',
 'feature_names': ['sepal length (cm)',
  'sepal width (cm)',
  'petal length (cm)',
  'petal width (cm)'],
 'filename': 'iris.csv',
 'data_module': 'sklearn.datasets.data'}

In [7]:
# 데이터 프레임 생성
data = pd.DataFrame(data=iris['data'], columns=iris['feature_names'])
target = pd.DataFrame(data=iris['target'], columns=['target'])

data

     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [8]:
target

     target
0         0
1         0
2         0
3         0
4         0
..      ...
145       2
146       2
147       2
148       2
149       2

[150 rows x 1 columns]

In [9]:
df = pd.concat([data, target], axis=1)

df.to_csv('iris.csv', index=False)

df

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
4,5.0,3.6,1.4,0.2,0
...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,2
146,6.3,2.5,5.0,1.9,2
147,6.5,3.0,5.2,2.0,2
148,6.2,3.4,5.4,2.3,2
149,5.9,3.0,5.1,1.8,2

In [10]:
df = pd.read_csv('iris.csv')

df

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
4,5.0,3.6,1.4,0.2,0
...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,2
146,6.3,2.5,5.0,1.9,2
147,6.5,3.0,5.2,2.0,2
148,6.2,3.4,5.4,2.3,2
149,5.9,3.0,5.1,1.8,2

In [11]:
# 학습 데이터, 테스트 데이터 분류
X_train, X_test, y_train, y_test = train_test_split(data, target, test_size=0.2, random_state=11)

In [12]:
X_train

     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
120                6.9               3.2                5.7               2.3
122                7.7               2.8                6.7               2.0
49                 5.0               3.3                1.4               0.2
29                 4.7               3.2                1.6               0.2
..                 ...               ...                ...               ...
76                 6.8               2.8                4.8               1.4
13                 4.3               3.0                1.1               0.1
81                 5.5               2.4                3.7               1.0
91                 6.1               3.0                4.6               1.4
80                 5.5               2.4                3.8               1.1

[120 rows x 4 columns]

In [13]:
X_test

     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
112                6.8               3.0                5.5               2.1
145                6.7               3.0                5.2               2.3
133                6.3               2.8                5.1               1.5
56                 6.3               3.3                4.7               1.6
111                6.4               2.7                5.3               1.9
9                  4.9               3.1                1.5               0.1
65                 6.7               3.1                4.4               1.4
15                 5.7               4.4                1.5               0.4
30                 4.8               3.1                1.6               0.2
63                 6.1               2.9                4.7               1.4
119                6.0               2.2                5.0               1.5
62                 6.0               2.2                4.0               1.0
84                 5.4               3.0                4.5               1.5
113                5.7               2.5                5.0               2.0
139                6.9               3.1                5.4               2.1
41                 4.5               2.3                1.3               0.3
103                6.3               2.9                5.6               1.8
66                 5.6               3.0                4.5               1.5
110                6.5               3.2                5.1               2.0
142                5.8               2.7                5.1               1.9
69                 5.6               2.5                3.9               1.1
2                  4.7               3.2                1.3               0.2
22                 4.6               3.6                1.0               0.2
51                 6.4               3.2                4.5               1.5
12                 4.8               3.0                1.4               0.1
11                 4.8               3.4                1.6               0.2
149                5.9               3.0                5.1               1.8
75                 6.6               3.0                4.4               1.4
16                 5.4               3.9                1.3               0.4
85                 6.0               3.4                4.5               1.6

In [14]:
y_train

     target
0         0
120       2
122       2
49        0
29        0
..      ...
76        1
13        0
81        1
91        1
80        1

[120 rows x 1 columns]

In [15]:
y_test

     target
112       2
145       2
133       2
56        1
111       2
9         0
65        1
15        0
30        0
63        1
119       2
62        1
84        1
113       2
139       2
41        0
103       2
66        1
110       2
142       2
69        1
2         0
22        0
51        1
12        0
11        0
149       2
75        1
16        0
85        1

In [16]:
# 모델 생성
dt_clf = DecisionTreeClassifier(random_state=11)

In [18]:
# 학습 수행
dt_clf.fit(X_train, y_train)

DecisionTreeClassifier(random_state=11)

In [19]:
# 예측
pred = dt_clf.predict(X_test)

pred

array([2, 2, 1, 1, 2, 0, 1, 0, 0, 1, 1, 1, 1, 2, 2, 0, 2, 1, 2, 2, 1, 0,
       0, 1, 0, 0, 2, 1, 0, 1])

In [20]:
y_test

     target
112       2
145       2
133       2
56        1
111       2
9         0
65        1
15        0
30        0
63        1
119       2
62        1
84        1
113       2
139       2
41        0
103       2
66        1
110       2
142       2
69        1
2         0
22        0
51        1
12        0
11        0
149       2
75        1
16        0
85        1

In [22]:
pred

array([2, 2, 1, 1, 2, 0, 1, 0, 0, 1, 1, 1, 1, 2, 2, 0, 2, 1, 2, 2, 1, 0,
       0, 1, 0, 0, 2, 1, 0, 1])

In [25]:
from sklearn.metrics import accuracy_score
print('예측 정확도: {0:.4f}'.format(accuracy_score(y_test, pred)))

예측 정확도: 0.9333

In [28]:
# 예측하기
new_data = [[5.1, 3.0, 3, 1.2]]
new_pred = dt_clf.predict(new_data)

new_pred

C:\Users\ITSC\PycharmProjects\PythonProject\.venv\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(

array([1])

In [29]:
# 학습 모델 덤프
import joblib
joblib.dump(dt_clf, 'model.joblib')

['model.joblib']

In [30]:
# 학습 모델 로드(불러오기)
load_model = joblib.load('model.joblib')

In [31]:
# 예측하기
load_model.predict(new_data)

C:\Users\ITSC\PycharmProjects\PythonProject\.venv\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(

array([1])